### ISSUE TITLE
flutter3.3 和 flukit3.0.1似乎不兼容

### ISSUE THREAD

**Issue by specialbiscuit** [flutterchina/flukit#33]
E/flutter ( 7676): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a 
null value
E/flutter ( 7676): #0      ScrollPosition.viewportDimension (package:flutter/src/widgets/scroll_position.dart:177:53)
E/flutter ( 7676): #1      _PagePosition.getPixelsFromPage (package:flutter/src/widgets/page_view.dart:390:19)
E/flutter ( 7676): #2      PageController.animateToPage (package:flutter/src/widgets/page_view.dart:203:16)
E/flutter ( 7676): #3      _SwiperState.animateToPage (package:flukit/src/swiper.dart:447:11)
E/flutter ( 7676): #4      _SwiperState._start.<anonymous closure> (package:flukit/src/swiper.dart:408:7)
E/flutter ( 7676): #5      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter ( 7676): #6      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter ( 7676): #7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
E/flutter ( 7676):

**Comment by yanashenyang** [comment]
same same
